"""
Metric specification contract generated by scout for playground-series-s6e9.
"""

from typing import Callable
import numpy as np
from evaluation.metrics import MetricRegistry

COMPETITION_ID = "playground-series-s6e9"
OFFICIAL_METRIC = "roc_auc"
METRIC_DIRECTION = "maximize"


def score(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    """Scikit-learn compatible scoring interface: score(y_true, y_pred) -> float."""
    return MetricRegistry.roc_auc(y_true, y_pred)


def get_scorer() -> tuple[Callable[[np.ndarray, np.ndarray], float], str]:
    return score, METRIC_DIRECTION
